spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:
    tomcat:
        default-transaction-isolation: -1
        initial-size: 50
        max-active: 120
        min-idle: 50
        max-idle: 120
        max-wait: 3000
        suspect-timeout: 60
        time-between-eviction-runs-millis: 30000
        min-evictable-idle-time-millis: 60000
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        validation-query: SELECT 1
        validation-interval: 30000
        remove-abandoned: true
        remove-abandoned-timeout: 60
        default-auto-commit: null